research_topic:
  description: >
    Research the provided topic of {topic} to gather the most important information that will 
    be useful in creating a book outline. Ensure you focus on high-quality, reliable sources.
    Please write the output entirely in Japanese.

    Here is some additional information about the author's desired goal for the book:

    {goal}
  expected_output: >
    A list of key facts, statistics, and contextual information that should be used for creating a logical book outline in Japanese.
  agent: researcher

generate_outline:
  description: >
    Based on the research findings, create a JSON-formatted book outline consisting of a list of chapters.
    Each chapter must contain:
    - a `title` (Japanese)
    - a `description` (Japanese, brief but informative)
    
    Format your output as a JSON list of objects, like so:
    [
      {"title": "第1章：AIの歴史", "description": "人工知能の起源から現代までの進化を概観します。"},
      ...
    ]

    Ensure no duplicate or overlapping chapters, and keep each chapter under 3,000 words in scope.

    Here is some additional information about the author's desired goal for the book:

    {goal}
  expected_output: >
    A JSON-formatted list of chapter objects, each containing a `title` and `description`, in Japanese.Remember to return JSON object.
  agent: outliner